I'm sorry, but an uncaught exception occurred.

While running game code:
  File "script.rpy", line 232, in script call
    call monastry_map_loc
  File "script.rpy", line 247, in script call
    call screen monastry_map
  File "add.rpy", line 639, in script
    python:
  File "add.rpy", line 643, in <module>
    renpy.image("/storage/castellan_coins_idle.png", itempic)
Exception: Images may only be declared inside init blocks.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "script.rpy", line 232, in script call
    call monastry_map_loc
  File "script.rpy", line 247, in script call
    call screen monastry_map
  File "add.rpy", line 639, in script
    python:
  File "D:\renpy-8.0.2-sdk\renpy\ast.py", line 1131, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\renpy-8.0.2-sdk\renpy\python.py", line 1052, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "add.rpy", line 643, in <module>
    renpy.image("/storage/castellan_coins_idle.png", itempic)
  File "D:\renpy-8.0.2-sdk\renpy\exports.py", line 322, in image
    raise Exception("Images may only be declared inside init blocks.")
Exception: Images may only be declared inside init blocks.

Windows-10-10.0.19042 AMD64
Ren'Py 8.0.2.22081402
randal_may_monastry 1.0
Sat Aug 20 01:59:51 2022
